UBUNTU: SAUCE: Fix a buidling error when turn off CONFIG_SMP
BugLink: http://bugs.launchpad.net/bugs/647890

Commit bde95e1bcf0b39b06c365e509dc4e11bfcbb54e5 introduced a building
error:
--
/opt/git/Ubuntu/roc/ubuntu-maverick/arch/arm/mm/ioremap.c: In function '__arm_multi_strided_ioremap':
/opt/git/Ubuntu/roc/ubuntu-maverick/arch/arm/mm/ioremap.c:437: error: 'size' undeclared (first use in this function)
/opt/git/Ubuntu/roc/ubuntu-maverick/arch/arm/mm/ioremap.c:437: error: (Each undeclared identifier is reported only once
/opt/git/Ubuntu/roc/ubuntu-maverick/arch/arm/mm/ioremap.c:437: error: for each function it appears in.)
make[3]: *** [arch/arm/mm/ioremap.o] Error 1
make[2]: *** [arch/arm/mm] Error 2
make[2]: *** Waiting for unfinished jobs....
--

This patch fixed this.

Cc: Lajos Molnar <molnar@ti.com>
Signed-off-by: Bryan Wu <bryan.wu@canonical.com>
Signed-off-by: Tim Gardner <tim.gardner@canonical.com>