UBUNTU: sms1xxx: fix missing #include <linux/types.h> OriginalAuthor: Michael Krufky <mkrufky@linuxtv.org> OriginalLocation: http://git.kernel.org/?p=linux/kernel/git/torvalds/linux-2.6.git;a=commitdiff_plain;h=2c6a37bb076b9718c6362d4ffa1c7e58fdb1a0e9 Bug: #308719
Fix the build error:

smscoreapi.c:689: error: 'uintptr_t' undeclared

Thanks to Peter Schlaf for reporting this.

Cc: Peter Schlaf <peter.schlaf@web.de>
Signed-off-by: Michael Krufky <mkrufky@linuxtv.org>
Signed-off-by: Mauro Carvalho Chehab <mchehab@infradead.org>